// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfhX6AHdb8SfeQujEj57DHS3p1V8gyeYI',
    appId: '1:858733852798:web:6dc4f77623e2c8fdfb002f',
    messagingSenderId: '858733852798',
    projectId: 'nike-5ef76',
    authDomain: 'nike-5ef76.firebaseapp.com',
    storageBucket: 'nike-5ef76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJ0OqklgjCEHPV0S5Ajne29627HD77HE',
    appId: '1:858733852798:android:d57df94bfe353a41fb002f',
    messagingSenderId: '858733852798',
    projectId: 'nike-5ef76',
    storageBucket: 'nike-5ef76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzbZZTjtqjs-TYB8m_EPF-YfcbZ6aeFJ0',
    appId: '1:858733852798:ios:bda11566e132ab02fb002f',
    messagingSenderId: '858733852798',
    projectId: 'nike-5ef76',
    storageBucket: 'nike-5ef76.firebasestorage.app',
    iosBundleId: 'com.example.nike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzbZZTjtqjs-TYB8m_EPF-YfcbZ6aeFJ0',
    appId: '1:858733852798:ios:bda11566e132ab02fb002f',
    messagingSenderId: '858733852798',
    projectId: 'nike-5ef76',
    storageBucket: 'nike-5ef76.firebasestorage.app',
    iosBundleId: 'com.example.nike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfhX6AHdb8SfeQujEj57DHS3p1V8gyeYI',
    appId: '1:858733852798:web:40ee1206c4a0dcddfb002f',
    messagingSenderId: '858733852798',
    projectId: 'nike-5ef76',
    authDomain: 'nike-5ef76.firebaseapp.com',
    storageBucket: 'nike-5ef76.firebasestorage.app',
  );
}
